### PR TITLE
Always parse and return data

### LINKED ISSUE #248: Custom error object
Right now the error object returns data associated with the status of the failed requested (status code and name). In most of my use cases the server returns an error message that is displayed to the user. The only way i can consume this message now is by adding an extra state hook for the error and setting it manually. 

It would be great if the error object could be leveraged to pass on the error message. Perhaps a function can be passed that provides the response details or body and can be used to either construct a custom error object or add properties to the current error object.

### PR DESCRIPTION
**Pull request by YassienW**
Gives access to response data even when response.ok is false. Allows for more customization based on returned data and saves having to parse data on errors.

Fixes #248

### CODE REVIEW

File: src/utils.ts [hunk 1]
```diff
@@ -149,7 +149,7 @@ export const tryGetData = async (res: Response | undefined, defaultData: any, re
   if (typeof responseType === 'undefined') throw Error('responseType cannot be undefined... 😵')
   const types = (Array.isArray(responseType) ? responseType : [responseType]) as ResponseType
   if (types[0] == null) throw Error('could not parse data from response 😵')
-  const data = res.ok ? await tryRetry(res, types) : undefined
+  const data = tryRetry(res, types)
```
Comment (alex-cory) [inline src/utils.ts:152]: this must be `await`ed

Comment (YassienW) [reply src/utils.ts:152]: Oops, fixed

**Comment by alex-cory** [comment]
This broke some of the tests. You need to make sure to run the tests. `yarn test:browser:watch`

**Comment by YassienW** [comment]
The [part of the test](https://github.com/ava/use-http/blob/master/src/__tests__/useFetch.test.tsx#L1084) in question expects the value of data to be equal to `data` passed on in the options, which will not be the case after this change. 

Should i go ahead and delete that line? It wouldn't compromise what the test is checking for anyway which is the validity of the error object.

**Comment by alex-cory** [comment]
You will need to fix useFetch so that when `undefined` is the value of the response data, it will use the default.

**Comment by alex-cory** [comment]
Change [this line](https://github.com/ava/use-http/blob/master/src/__tests__/useFetch.test.tsx#L1073) to `fetch.mockResponse(() => Promise.reject(makeError(401, 'Unauthorized')))`

**Comment by alex-cory** [comment]
this should work in `v1.0.9`

**Comment by YassienW** [comment]
Thanks, i appreciate the quick updates!
